### ISSUE TITLE
`JSONField` should set class attr `cache_ok = False`

### ISSUE THREAD

**Issue by Kache** [penguinolog/sqlalchemy_jsonfield#22]
Behavior is the same as the current `cache_ok = None`, except it emits a SqlAlchemy warning at: https://github.com/sqlalchemy/sqlalchemy/blob/1da3f3455dc97ad095d7abd10add7f12efe6c1c7/lib/sqlalchemy/sql/type_api.py#L1298-L1306

Relevant documentation is also in the same file:
 * https://github.com/sqlalchemy/sqlalchemy/blob/1da3f3455dc97ad095d7abd10add7f12efe6c1c7/lib/sqlalchemy/sql/type_api.py#L1549-L1557
 * https://github.com/sqlalchemy/sqlalchemy/blob/1da3f3455dc97ad095d7abd10add7f12efe6c1c7/lib/sqlalchemy/sql/type_api.py#L1148

Otherwise if there's a way to make it SqlAlchemy cacheable, could be set to `True`

**Comment by penguinolog** [comment]
Fixed in version 1.0.2
